#数据源配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    # 一、WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
    druid:
      web-stat-filter:
        #是否启用StatFilter默认值false
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: "true"
  #        session-stat-max-count:
  #        principal-session-name:
  #        principal-cookie-name:
  #        profile-enable:
      #二、是否启用StatViewServlet（监控页面）默认值为false（考虑到安全问题默认并未启动，如需启用建议设置密码或白名单以保障安全）
      stat-view-servlet:
        # Spring监控配置，说明请参考Druid Github Wiki，配置_Druid和Spring关联监控配置
        enabled: true
        url-pattern: "/druid/*"
        reset-enable: "true"
        login-username: "admin"
        login-password: "admin"
        allow: "192.168.0.100,127.0.0.1"
        deny: "192.168.0.101"
      #三、Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: "com.cobra.mybatisdemo.service.impl.*"
  redis:
    host: 192.168.60.129
    port: 6379
#mybatis映射配置
mybatis:
  mapper-locations: classpath:mapping/*.xml
#日志输出sql语句
logging:
  level:
    com.cobra.mybatisdemo.dao: debug