package com.cobra.mybatisdemo.dataobject;

import java.math.BigDecimal;

public class OrderInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_id
     *
     * @mbg.generated Sat Mar 16 10:50:50 CST 2019
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_desc
     *
     * @mbg.generated Sat Mar 16 10:50:50 CST 2019
     */
    private String orderDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_fee
     *
     * @mbg.generated Sat Mar 16 10:50:50 CST 2019
     */
    private BigDecimal orderFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.user_id
     *
     * @mbg.generated Sat Mar 16 10:50:50 CST 2019
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_id
     *
     * @return the value of order_info.order_id
     *
     * @mbg.generated Sat Mar 16 10:50:50 CST 2019
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_id
     *
     * @param orderId the value for order_info.order_id
     *
     * @mbg.generated Sat Mar 16 10:50:50 CST 2019
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_desc
     *
     * @return the value of order_info.order_desc
     *
     * @mbg.generated Sat Mar 16 10:50:50 CST 2019
     */
    public String getOrderDesc() {
        return orderDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_desc
     *
     * @param orderDesc the value for order_info.order_desc
     *
     * @mbg.generated Sat Mar 16 10:50:50 CST 2019
     */
    public void setOrderDesc(String orderDesc) {
        this.orderDesc = orderDesc == null ? null : orderDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_fee
     *
     * @return the value of order_info.order_fee
     *
     * @mbg.generated Sat Mar 16 10:50:50 CST 2019
     */
    public BigDecimal getOrderFee() {
        return orderFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_fee
     *
     * @param orderFee the value for order_info.order_fee
     *
     * @mbg.generated Sat Mar 16 10:50:50 CST 2019
     */
    public void setOrderFee(BigDecimal orderFee) {
        this.orderFee = orderFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.user_id
     *
     * @return the value of order_info.user_id
     *
     * @mbg.generated Sat Mar 16 10:50:50 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.user_id
     *
     * @param userId the value for order_info.user_id
     *
     * @mbg.generated Sat Mar 16 10:50:50 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Override
    public String toString() {
        return "OrderInfo{" +
                "orderId=" + orderId +
                ", orderDesc='" + orderDesc + '\'' +
                ", orderFee=" + orderFee +
                ", userId=" + userId +
                '}';
    }

}