package com.cobra.mybatisdemo.dao;

import com.cobra.mybatisdemo.dataobject.OrderInfo;
import com.cobra.mybatisdemo.dto.OrderDTO;

import java.util.List;

public interface OrderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Mar 16 10:50:50 CST 2019
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Mar 16 10:50:50 CST 2019
     */
    int insert(OrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Mar 16 10:50:50 CST 2019
     */
    int insertSelective(OrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Mar 16 10:50:50 CST 2019
     */
    OrderInfo selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Mar 16 10:50:50 CST 2019
     */
    int updateByPrimaryKeySelective(OrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Mar 16 10:50:50 CST 2019
     */
    int updateByPrimaryKey(OrderInfo record);

    /**
     * 根据UserId查找订单
     * @param userId
     * @return
     */
    List<OrderInfo> selectByUserId(Integer userId);

    /**
     * 根据UserId查找OrderDTO
     * @param userId
     * @return
     */
    List<OrderDTO> selectOrderDTOListByUserId(Integer userId);

}